### ISSUE TITLE
ws_fnc createGarrison: add ASR AI way to stop units

### ISSUE THREAD

**Issue by shadow-fa** [folkarps/F3#117]
Iff stopping of garrisoned units is broken with `asr_ai`, then `asr_ai` specific code should probably be added to prevent this.

**Comment by SamLex** [comment]
Possibly relevant information: http://www.folkarps.com/forum/viewtopic.php?f=48&t=2358

**Comment by shadow-fa** [comment]
@Raptoer Do we use/have an asr-ai version which has the feature we need for this?

**Comment by Raptoer** [comment]
@shadow-fa I think that forum post is still valid, although it might not be in future releases, since PE_ASR is being merged into base ASR.
