### ISSUE TITLE
 Wiki: Document all F3 components.

### ISSUE THREAD

**Issue by shadow-fa** [folkarps/F3#125]
The comments in the code still refer to the wiki at `http://ferstaberinde.com/f3/en`, 
but since we have new and changed components I think these links should be removed (or replaced). 
Although, strictly speaking it's just linking there because of the `Credits`, not for the documentation.
Maybe we should just add the link to our wiki as well?

Additionally (and most importantly) we should document all components in our own wiki here:
<https://github.com/Raptoer/F3/wiki>

**Comment by SamLex** [comment]
I also think we should make an effort to add file header comments to functions and such explaining functionality and parameters.

**Comment by shadow-fa** [comment]
Closing in favor of #159
