### ISSUE TITLE
Remove Group ID

### ISSUE THREAD

**Issue by shadow-fa** [folkarps/F3#131]
Call signs have been transferred to the 3DEN field in these commits:
62b5e5cc8216280e4a240011af4579ac2ba2e13b
141f943cbca791a2e46d0bf53cdc9a19554bb413

So the Group ID component has become obsolete, because the 3den callsign field does exactly the same thing.
~~I can only assume that it was an oversight that this component has not been deleted when this change was made.~~

Three call signs are different in the mission.sqm and would have to be updated, 
so that everything is exactly the same after removing the component.
```sqf
// [group, component callsign, in-editor callsign]
["GrpFIA_IFV1","FIA TECH1 -","FIA IFV1 -"]
["GrpFIA_IFV2","FIA TECH2 -","FIA IFV2 -"]
["GrpGEN_MK","Gendarmerie Marksman -","Gendarmerie MK -"]
```

#### Further information:
The component was marked as legacy and disabled by default here: dbae4a8c14cbb279ed7fcbec6d305b05117712a3
But 2 weeks later reenabled for some reason: 3e5145ae9b9a4397c4d3c39720a5b0e0d633b049
But, the re-enabling wasn't complete, so one line was not re-enabled: 
https://github.com/ferstaberinde/F3/commit/dbae4a8c14cbb279ed7fcbec6d305b05117712a3#diff-22ca35f6643bbfc31cdf4bfb83c69d47R8 which lead to the problem (which no one noticed until now?), that the ORBAT used the 3den callsigns whereas everything else (e.g. sideChat) used the callsigns from the component. (Edit: This has since then been fixed in #141)

**Edit:**
https://feedback.bistudio.com/T118543
It turns out this bug still exists, and this might be a deal-breaker for us, since a lot of missionmakers copy and paste units from (the template into other missions). (e.g. when doing orbat changes)

**Comment by NikkoJT** [comment]
Does the in-editor callsign field actually work the same way? I thought the reason for GroupID was that the editor callsign does not reliably work across all clients in multiplayer.

I recall running into some issues myself, where units with only editor callsigns would display autogenerated "Alpha 1-1" callsigns for clients, rather than the custom callsign they'd been given.

**Comment by shadow-fa** [comment]
It might be the case that the 3den solution is not JIP-safe. I will investigate this further soon.

**Comment by shadow-fa** [comment]
Blocked by two game bugs:
* https://feedback.bistudio.com/T118543 Can't copy/cut & paste groups.
* not JIP safe. JIP/Reconnected players don't see the custom callsign/groupID

**Comment by SamLex** [comment]
@shadow-fa Think we should just close this as BI is unlikely to fix this anytime soon?
