### ISSUE TITLE
Add component to delete vehicles assigned to un-slotted elements

### ISSUE THREAD

**Issue by NikkoJT** [folkarps/F3#153]
As mentioned in Discord.
This theoretical component would receive parameters for a vehicle and its assigned group, in a manner similar to the Authorised Crew component. If the assigned group is not slotted, the component would delete the vehicle on mission start.

This component would be optional, to be used in cases where extra empty vics would be misleading or inconvenient.

Shado suggested the Premount component as a base to build this on. However, SK raised the point that vehicles this is used with may not be premounted.

Prototype single-vic implementation follows:

```
_list_ifv2 = (crew vehNATO_IFV2);

	if  (count _list_IFV2 == 0) then {
		deletevehicle vehNATO_IFV2};
```

alternatively, SK's version:

```
if ((isServer) && (!isNil "GrpCSAT_AH1")) then {{deleteVehicle _x} forEach (crew JTAC_CAS); deleteVehicle JTAC_CAS;};
```

**Comment by shadow-fa** [comment]
> Shado suggested the Premount component as a base to build this on. However, SK raised the point that vehicles this is used with may not be premounted.

It doesn't have to be based on premount, but premount could call this function (by default / if enabled). Maybe it could just be a seperate function (within the premount component directory) that we also call in `init.sqf` with a missionmaker-defined list of vehicles/crew.

Should I implement this (as a prototype), or does this still need more discussion beforehand?

**Comment by NikkoJT** [comment]
3 years on, I have some doubts about whether this is necessary or could even be implemented in a sensible way. I'm open to dropping this idea.

**Comment by Aqarius90** [comment]
You could just deleteVehicle if it's crew (or dismounts) don't exist, but that would probably screw with reinforcements in some fresh and fun way.

**Comment by costno** [comment]
I think this probably can be dropped, repeating what others said about potentially screwing with reinforcements. 

I think we have enough of a cultural standard of 'don't take equipment not assigned to you' and just have to keep that up with Host's paying attention to elements trying to take 6 vehicles and tell them not to.

Or, we do this clean up on unused vehicles but have a 'depot' asset/tool for mission makers to allow reinforcements or element leaders to create an appropriate vehicle on the fly.
