### ISSUE TITLE
Template: enable data linking for units with laser designators

### ISSUE THREAD

**Issue by NikkoJT** [folkarps/F3#184]
Beyond-line-of-sight (BLOS) applications of the hand-held laser designator require datalink sending to be enabled in the attributes of the unit holding it. BLOS applications include lock-on-after-launch missiles, and the Mk41 VLS.

To make it easier to plug in LOAL and the Mk41, datalink sending should be enabled by default on units such as the JTAC. Enabling datalink send on _all_ units would also be acceptable to avoid confusion.

Whether to also enable datalink send by default on vehicles with laser designators is a question for consideration - I personally don't see any downside to doing it.

Datalink send is enabled by a checkbox in the unit's editor attributes, or using the setVehicleReportRemoteTargets command.

**Comment by shadow-fa** [comment]
Enabling this on all units and vehicles could potentially lead to performance issues (especially in multiplayer)?
Because every unit/vehicle(?) would constantly broadcast a list of targets to all other units?
This might require some testing.

**Comment by SamLex** [comment]
- All playable infantry in the template will be given the send data link capability via EDEN attributes
- All vehicles in the template with lasers (off the top of my head: striders, AHs, jets, some THs) will be given the send data link capability via EDEN attributes
- All vehicles in the template with lock-on-laser munitions by default or capable via dynamic loadout (off the top of my head: AHs, jets) will be given the receive data link capability via EDEN attributes

**Comment by SamLex** [comment]
Currently blocked on #212 as this also affects 3IFB.

**Comment by SamLex** [comment]
For future reference, this was implemented using the following commands in the 3DEN debug console.

Find all playable units of kind "Man", set their "ReportRemoteTargets" attribute to true
```
((all3DENEntities # 0) select {_x isKindOf "Man" && _x in playableUnits}) apply {_x set3DENAttribute ["ReportRemoteTargets", true]}
```

Find all non-"Man" objects with a turret weapon with a name containing "laser", set its "ReportRemoteTargets" attribute to true
```
(((all3DENEntities # 0) select {!(_x isKindOf "Man")}) select {private _unit = _x; count ((allTurrets _unit) select {count ((_unit weaponsTurret _x) select {toLower _x find "laser" != -1}) > 0}) > 0}) apply {_x set3DENAttribute ["ReportRemoteTargets", true]}
```
Find all non-"Man" objects with a pylon that accepts magazines with a name containing "lg",  "pg", "bomb_04", or "bomb_03"*; set its "ReceiveRemoteTargets" attribute to true
```
((all3DENEntities # 0) select {!(_x isKindOf "Man")}) select {private _unit = _x; count ((_unit getCompatiblePylonMagazines "") select {count (_x select {private _mag = toLower _x; ((_mag find "lg") != -1) || ((_mag find "pg") != -1) || ((_mag find "bomb_04") != -1) || ((_mag find "bomb_03") != -1)}) > 0}) > 0} apply {_x set3DENAttribute ["ReceiveRemoteTargets", true]}
```

\* derived from list of laser guided munitions on the wiki

**Comment by SamLex** [comment]
Done in FA.3.5.3
