### ISSUE TITLE
[assignGear] Add bags to more vehicles

### ISSUE THREAD

**Issue by SamLex** [folkarps/F3#203]
Bags are currently only added to medium and heavy helicopters. This issue is to discuss adding them to others.

**Comment by NikkoJT** [comment]
I think it's worth adding them to IFVs, trucks, and tanks. For lighter vehicles, I don't think it makes as much sense, and we're more likely to keep the vehicle nearby anyway.

(This should probably be accompanied by some doctrinal reinforcement to discourage people from grabbing the bags and taking everything from the vic at mission start, but that's outside F3's scope)

**Comment by SamLex** [comment]
- 2 bags should be added to tanks (v_tank) and IFVs (v_ifv) to mirror medium helicopters.
- 4 bags should be added to trucks (v_tr) to mirror heavy helicopters.

**Comment by SamLex** [comment]
Currently blocked on #221 as this also affects 3IFB.

**Comment by SamLex** [comment]
Done in FA.3.5.3
