### ISSUE TITLE
Add snow weather parameter

### ISSUE THREAD

**Issue by NikkoJT** [folkarps/F3#204]
Recent changes to `setRain` and `rainParams` now enable us to add snow as an ordinary weather setting. According to Ciaran, this method has no notable performance impact. If this is proven in session testing, we should be able to add this to the F3 weather selector with no difficulty.

WAS: **Add Chozo's snow script to F3**
~~There is the potential to add darkchozo's snow script (as used in A Cold Day/XS) to F3. This script consists of two parts: one adding snow particles and frosty breath, and one adding snow on the ground. The first part is purely script-based and requires no textures; the second requires some small textures.~~

~~Note that the snow particle script is already available for seasonal use as a mod on the FA server.~~

~~If implemented into F3, the particle script could be added to Mission Conditions as a weather setting. The ground cover script has performance limitations and might not be suitable for addition.~~

**Comment by shadow-fa** [comment]
There might be a way to do the snow texture thing without actual textures.
This way it could be added to a admin/server mod as a script and used in all the missions.
In my opinion this would make far more sense than creating specialized christmas versions of missions.

**Comment by NikkoJT** [comment]
Parameters would be ideal, particularly in the case of the particle script. However, Aqarius noted, after testing it, that the ground cover script has a significant performance impact, on top of its already-limited draw distance (as well as other limitations such as disappearing in spectator). Given these issues I'm more inclined to believe the ground cover script should be left out - missions need to be tailored to it.

**Comment by NikkoJT** [comment]
Discovered that the server mod version of the snow particle script has a heavy performance impact. Would need to be investigated and resolved before including in F3.

**Comment by NikkoJT** [comment]
Session testing shows that performance is acceptable with the new rainparams. So, a snow parameter should now be reasonably easy to add. 

See also: https://forum.folkarps.com/viewtopic.php?f=48&p=17134#p17134

**Comment by NikkoJT** [comment]
Ciaran reports that cold breath clouds can be added too at minimal performance cost. Also potentially able to tie them in to the simulated ambient temperature in addition to the snow parameter.

**Comment by NikkoJT** [comment]
In 2.10 a snowflake texture is being added to base Arma which we can use for this.

\A3\Data_f\snowflake16_ca.paa

**Comment by NikkoJT** [comment]
Since 2.10, everything needed for this is in place.

**Comment by NikkoJT** [comment]
As I understand from looking at it, the coldBreath function won't apply to units created after the local init - for example, JIP players or script-spawned units. It would be good to account for that, if it's reasonably practical.
