### ISSUE TITLE
[assignGear] HSAM spotter loadout uses HMG bag

### ISSUE THREAD

**Issue by NikkoJT** [folkarps/F3#210]
AssignGear loadouts for the hsamag (HSAM team leader) classes use the _baghmgag instead of _baghsamag.

While this causes no issues in the standard template, as the items used for these bags are the same and interchangeable, it's misleading and could cause a problem if someone wanted to use the raised tripod for the HMG (since the raised tripods don't work with the Titans), or if they wanted to change what bag the HSAM leader has.

This issue appears to be present in both the light and standard versions of all faction assignGear files, except of course Gendarmerie which has no HSAM element.

**Comment by SamLex** [comment]
3ifb, syndikat, and CTRG hsamag don't have weapon bags
