### ISSUE TITLE
[assignGear] Smoke grenade variables not declared in fn_assigngear

### ISSUE THREAD

**Issue by NikkoJT** [folkarps/F3#211]
Where fn_assignGear.sqf declares all the variable names to use in assignGear scripts, the Blue and Purple grenades are not declared, despite being used in default loadouts. Red grenades aren't declared either though I'm not sure if they're used (probably should be declared though).

**Comment by SamLex** [comment]
Confirmed "_smokegrenadeblue" and "_smokegrenadepurple" are now declared in fn_assignGear.sqf
