### ISSUE TITLE
3.5.2 RC2 gear comparison.

### ISSUE THREAD

**Issue by Aqarius90** [folkarps/F3#213]
I remade the spreadsheet from a while ago for the 3.5.2-RC2, and shado asked me to raise an issue WRT discrepancies between various loadouts. Note, these are not necessarily bad thing, but having an overview is a good idea

### Light-Heavy difference (global)
* RAT: +1 ratmag2
* AAR: +bag, +1 ratmag1
* MAT (all three): +1 matmag2

Everything else is the same. I'd say this is enough to require defining loadouts by delta an option.

### Unit loadouts
AR

.|STD | NATO/NATOp | CSATp | CTRG
---|----|--------------|-------|------
#ARmag |2 | +2 | +2 | +1 
#ARmagtr |1 | +1 | +1 | - 
rnd/belt |200 | 100 | 100 | 150
rounds total |600 | 300+300 | 300+300 | 450+150

AAR

.|STD | NATO/NATOp | CSATp | CTRG
---|----|--------------|-------|------
#ARmag  |1 | +1 | +1 | +1 
rnd/belt |200 | 100 | 100 | 150
rounds total |200 | 100+100 | 100+100 | 150+150

Designated Marksman
* CSAT gets +5 DMriflemag
  * CSAT mags are 10rnd, vs 20rnd. Of note, NATO and NATO pacific get 30rnd mags, And NATO, NATOp, and CSATp get 6.5mm rifles (rest get 7.62)

RAT
* FIA AK gets +1 ratmag1
  * FIA AK gets RPG7s.

### Base loadouts
* Compared to other smgbase classes, SMG gets +2 SMG mags
  * Pure SMG is a frontline role.
* Compared to other smgbase classes, pilots get -1 smgmag,
  * Pilots have a pockets issue

### Vehicles
* Vehicles loadouts (files) are identical across factions. See this [comment](https://github.com/folkarps/F3/issues/213#issuecomment-462067504)

### Base Loadouts
* R, CAR and SMG lose one frag.
  * No idea.
    * Take away one more. That way all units can fit the [base]+[weapon]+[2xsmoke/2xfrag].
      * Changed in #215
* MATG/HATG/HMGG/MSAMG/HSAMG get -2 carbine mags
  * Weight reduction, maybe?
    * give them +2 mags, to conform to carbine module
      * Changed in #215
* JTAC and CO both have 9 glsmokes, CO gets all white, JTAC gets all reds
  * Consider putting together a mix.
    * Changed in #215. CO gets 4/2/2 and JTAC 3/3/2 white/red/green gl smokes

#### Discrepancies between heavy faction loadouts
MAT
* CTRG, FIA AK get no heavy bonus
  * Changed in #215
* Syndikat get extra +1 matmag1
  * Changed in #215

RAT
* FIA AK gets ratmag1 instead of ratmag2
  * Now also using ratmag2 in #215

AAR
* Syndikat and FIA AK get bag in light loadout, instead of heavy
  * Changed in #215. Heavy loadouts need bags because of the RATmag. light loadouts get no bag.

### Discrepancies between unit loadouts
Weapon randomization
* FIA Rifles and carbines are randomized from an array
  * Moved selectRandom in #215

Guerilla loadouts
* FIA, FIA AK, and Syndikat get 2 extra smoke grenades for all units except SL, CO, JTAC and Jet Pilot.  Pilot gets nothing, SL, CO and JTAC *lose* two smokes
  * Changed in #215 
* FIA, AK and Syndikat officers (CO, SL, FTL, JTAC, SP) don't get laser pointers
  * Suggest setting _attach1 to "" rather than handling it in assignment script.
    * Changed in #215
* FIA, FIA AK, and Syndikat SL loses 3 glsmokered
  * Added glsmokered to match other factions in #215 
* Some FIA, FIA AK, and Syndikat units (HSAML, MSAML, MSAMAG, MTRAG, HATL,HATAG, MATL, MATAG, HMTL, MGTL, MGAG, DM) lose 2 frags. Or, rather, all other factions *get extra* two frags.
  * Compensation for smokes?
    * Revise which units and why?
      * Changed to match other factions in #215
* FIA, FIA AK, and Syndikat FLT loses 3 glsmokewhite
  * Compensation for smokes?
    * Changed to match other factions in #215

Designated Marksman
* NATO, NATO pacific DM gets -2 DMmag, +2 DMmag_tr
  * Other DMRs are srifle classes, and have no tracer mags
    * Suggest _DMmag = _DMmag_tr for non-NATO, homogenize
      * Changed in #215

CO
* AAF gets -2 glsmokewhite
  * Changed in #215
* FIA AK gets -1 smokepurple
  * Changed in #215

SL
* FIA AK gets -1 smokepurple
  * Changed in #215

Carabineer
* CSAT Pacific, CTRG carabineer classes get rifles.
  * Suggest declaring _carbine = _rifle, and homogenizing
    * _carbine had the same value as _rifle anyway. Changed gear files to match others in #215. (Nothing effectively changed)

Sniper
* FIA AK and Syndikat get -3 sniper mags
  * Added mags in #215

JTAC
* Syndikat gets -1 pistol mag
  * Changed in #215

**Comment by NikkoJT** [comment]
> * Suggest _DMmag = _DMmag_tr for non-NATO

I don't think we should do things like this. Faction assignGear should be laid out the same way for all factions to avoid missionmaker confusion. Differences should be in what the gear is, not how it's assigned.

Things like _DMriflemag_tr and _carbine may not be important for a particular standard loadout, but they should remain as options in case the missionmaker wants to use different weapons. Same as how the assistant gunner tripod bags are all the same item by default, but are different variables because they _can_ be different.

Also, can you clarify what you mean by "homogenize" in this context?

>JTAC and CO both have 9 glsmokes, CO gets all white, JTAC gets all reds
>* Consider putting together a mix.

I suspect this is intended to encourage a distinction between cover smoke and signalling smoke.

**Comment by Aqarius90** [comment]
> RE: homogenisation

Maybe a bad term, basically the idea of making all assignGear scripts the same "pattern", so that later on we could make them the same script.
In practice, the assignGear.sqf  and assignGear_light.sqf for NATO look something like this:
>_DMrifle = "arifle_MXM_F";
>_DMriflemag = "30Rnd_65x39_caseless_mag";
>_DMriflemag_tr = "30Rnd_65x39_caseless_mag_Tracer";

>_unit addmagazines [_DMriflemag, 1];
>_unit addweapon _DMrifle;
>_unit addmagazines [_DMriflemag, 4];
>_unit addmagazines [_DMriflemag_tr, 2];

for NATO, and:
>_DMrifle = "srifle_EBR_F";
>_DMriflemag = "20Rnd_762x51_Mag";

>_unit addmagazines [_DMriflemag, 1];
>_unit addweapon _DMrifle;
>_unit addmagazines [_DMriflemag, 6];

for everyone else.  Changing the assignGear.sqf of non-NATO factions to _DMriflemag_tr =_DMriflemag would 
1) let us feed them through the NATO version of assignGear_light.sqf, and 
2) confine changes a user needs to make to assignGear.sqf if, say, they want to give AAF a DM with tracers.

The *actual* solution is probably to parametrize the mag count and pull it to faction definition entirely (something like _DMrifle = [arifle_MXM_F, 20Rnd_762x51_Mag, 4, _DMriflemag_tr, 2]), but that's a bit more involved. I was mostly trying to point out the difference, and the reasons for the same.

>GLSmokes

I would suppose so, but 
1) Why is the CO laying that much smoke?
2) Wouldn't it be better to have options when signalling instead of only red?
3) Would the CO have a need to signal too?
I'm not saying it should be changed, it's just a difference that I don't quite get.

**Comment by shadow-fa** [comment]
I wouldn't worry about implementation details at this time.

Years of tweaking single faction's gear files have led to the current state,
where there's minor differences across all files and nobody really knows why they exist.

**The point of this thread is to document and question all and any differences across gear files.**
Once we know why these differences exist, we can aim to remove some of them.
(Example: Why does FIA AK get less purple smokes)

We will not be taking away any flexibility, modifiability, or readability for mission makers.

The reason for this "homogenisation" is to not only sort out the mess that happened due to random changes to single gear files (where it may have been forgotten to change one or a few gear files), but also to have a cleaner starting point for any future assignGear code rework (e.g. #94)

**Comment by Aqarius90** [comment]
No. Only JTAC gets non-white GL smokes. CO and SL get purple 'nades, FTL gets two green 'nades, but GLare either white or HE-FRAG.

**Comment by costno** [comment]
So, from my recollection any smoke disparity is a carry over from previous F3 versions and some kind of drug/alcohol fueled pontificating (the best kind) about how guerrillas would fight compared to how a proper stand up gentleman would fight.  Which is to say, I'm in favor of normalising that kind of thing across factions and considering those disparities a mistake.  

Regarding AT, I don't think I even touched FIA AK, but they're kind of a frustrating side distraction that I'm tempted to suggest we just delete entirely to make room for the upcoming 3IFB who will have similar guns but sexier clothes, at which point they'll have identical AT to the rest of the factions which should be: 2 AT + 1 HE RAT, 1 AT AAR

Regarding other Ammo just normalize (homogenize?)  as best you can.  

Did I miss anything else in this thread that needs commenting on?

**Comment by shadow-fa** [comment]
Currently we have the following files for vehicle/create gear:
```
f_assignGear_aaf_v.sqf
f_assignGear_csat_v.sqf
f_assignGear_ctrg_v.sqf
f_assignGear_fia_v.sqf
f_assignGear_nato_v.sqf
f_assignGear_syndikat_v.sqf
```
All of them are exactly the same.

**Proposal:** Remove them all and only keep one file: `f_assignGear_v.sqf`.
I think we can also expect missionmakers to copy this file, change it, and include the new file instead of the default file (for the specific faction) when they want to change something for only one faction.

**Comment by shadow-fa** [comment]
>smoke disparity
I'm also in favor of normalising that.
However Aqarius might want to keep the guerilla factions seperate/different?

If we normalise them, do we want to give the non-guerilla factions more smokes or do we want to remove smokes from the guerilla factions?

**Comment by Aqarius90** [comment]
Thinking back, guerillas might get more smoke as compensation for overall lower amount of body armor. Though, outside PVP, that might not be an issue.

**Comment by shadow-fa** [comment]
```
* FIA, FIA AK, and Syndikat SL loses 3 glsmokered 
  * Compensation for smokes?
```
Can't be compensation, because guerilla SL/DC gets 2 _less_ smokes for some reason (in addition to the 3 red smokes they lose).
I think we should add the glsmokered and consider also giving them the same amount of smokes as the non-guerilla factions have.

**Comment by Aqarius90** [comment]
As I noted, I'm assuming the -2 smokes is supposed to be +2.

**Comment by SamLex** [comment]
Ok, I've edited the top comment to try and separate the original intent of this issue (documenting the differences) and the "mistakes" that are being changed. Let me know if you think I've made a mistake somewhere.

As for the remaining open questions, I'll address each below. In general, give the upcoming refactor in 3.6.0, I'm in favor of normalising most between factions, see how it goes, and do any "denormalisation" needed after the refactor (where it will hopefully be easier and nicer to do).

* Guerilla loadouts smoke differences
   * Normalise with non-guerilla
* DM tracer ammo
  * Normalise but avoid variable-variable assignment
* Pilots have less SMG ammo
  * Normalise if enough inventory space
* R, CAR and SMG lose one frag.
  * Go with Aqarius' suggestion
* MATG/HATG/HMGG/MSAMG/HSAMG get -2 carbine mags
  * Go with Aqarius' suggestion
* JTAC and CO both have 9 glsmokes, CO gets all white, JTAC gets all reds
  * Go with Costno's [suggestion](https://github.com/folkarps/F3/issues/213#issuecomment-461233349) of a mix with bias to white for CO and equal ratio for JTAC
* Re: Vehicle changes
  * Leave this for now, see above about refactor. Added note in top comment about it.

Any objections to the above changes?

**Comment by SamLex** [comment]
Done in FA.3.5.3
