### ISSUE TITLE
Move selectRandom in FIA gear

### ISSUE THREAD

**Issue by shadow-fa** [folkarps/F3#214]
Move `selectRandom` in FIA gear from here
`_unit addweapon (selectRandom _carbine);` (in `f_assignGear_fia_light.sqf`, `f_assignGear_fia_standard.sqf`)
and https://github.com/Raptoer/F3/blob/master/f/assignGear/f_assignGear_fiaAK_standard.sqf#L544
and https://github.com/Raptoer/F3/blob/master/f/assignGear/f_assignGear_fiaAK_light.sqf#L533
and https://github.com/Raptoer/F3/blob/master/f/assignGear/f_assignGear_fiaAK_light.sqf#L536
to
there https://github.com/Raptoer/F3/blob/master/f/assignGear/f_assignGear_fia.sqf#L103-L119

**Comment by SamLex** [comment]
Done in FA.3.5.3
