### ISSUE TITLE
Briefing Weather Report

### ISSUE THREAD

**Issue by SamLex** [folkarps/F3#222]
Briefing tab that summaries the mission weather, date and time. Supporting both FA3 and 3DEN weather settings.

**Comment by darkChozo** [comment]
So, [I've made a briefing screen](https://steamuserimages-a.akamaihd.net/ugc/763851539920272696/0474FCCF4ABD14D7C071B3A4A1C121F1C9EBAEEC/), and I'm looking for feedback. Looks/organization, functionality, more stuff that can be added, whatever.

Possible values for stuff:

Cloudiness: Overcast, Mostly Cloudy, Partly Cloudy, Clear
Rain: Heavy Rain, Rain, Light Rain, No Precipitation
Wind: High Winds, Windy, Light Winds (plus actual wind speed/direction in knots)
Fog: No Visibility, Heavy Fog, Foggy, Misty, Good Visibility, specifying the altitude if there is decay
Moon Phase: Full, Gibbous, Quarter, Crescent, New
