### ISSUE TITLE
[Template] CSAT IFV role spacing is inconsistent

### ISSUE THREAD

**Issue by NikkoJT** [folkarps/F3#225]
The CSAT IFV 2 Gunner role is written as "IFV2 Gunner" - all other IFV crew roles have a space between IFV and the number.

If we really want to get picky about this we could also consider adding a space in the CAS1 role descriptions.

**Comment by shadow-fa** [comment]
None of the group IDs (visible in chat) have a space though.

**Comment by NikkoJT** [comment]
> None of the group IDs (visible in chat) have a space though.

That's correct. I'm only talking about slotting role descriptions, which typically have a space between the team's type and number.

In the case of the CSAT IFV 2, the slotting screen looks like this:

CSAT IFV 1 Commander
CSAT IFV 1 Gunner
CSAT IFV 1 Driver (Repair)

CSAT IFV 2 Commander
CSAT IFV2 Gunner
CSAT IFV 2 Driver (Repair)

Clearly, the Gunner slot is inconsistent with how roles are usually formatted. All other IFV roles have a space. This is a pretty definitive error as it's not even consistent within the same team.

Theoretically, the CAS 1 slots should also have a space since the slotting role is a description, not their callsign (although the callsign is the same). I don't particularly care about this but it's a related point.

**Comment by SamLex** [comment]
Fixed in FA.3.5.3
