### ISSUE TITLE
[AssignGear] Use new unique magazine classes

### ISSUE THREAD

**Issue by NikkoJT** [folkarps/F3#233]
In an upcoming update, the Magazine Proxy system will be rolled out to vanilla A3. This system means magazine visual models are no longer tied to the weapon model, and as a result, different-coloured magazines now have different classes. For example, Sand, Green, and Black 6.5mm STANAG magazines all have different classes now, with each class appearing in the correct colour regardless of the colour of the weapon it's loaded into.

In backwards compatibility terms, we're functionally safe. Existing classes still work, currently defaulting to the Sand (6.5 STANAG), Black (5.56 30rd) and AKM (7.62x39) models. This may cause some visual mismatch in older missions, but nothing should break.

However, F3 loadouts going forward should probably be updated to use the new classes. Pacific NATO would get the green magazines, AK12 and AKM loadouts should get their appropriate magazines, etc.

Examples of new magazine classes:

"30Rnd_65x39_caseless_mag"; [existing class - sand]
"30Rnd_65x39_caseless_khaki_mag"; [new - Pacific]
"30Rnd_65x39_caseless_black_mag"; [new - black]
"30Rnd_762x39_AK12_Mag_Tracer_Green_F"; [new - AK12]
"30Rnd_762x39_Mag_F"; [existing class - AKM]
"30Rnd_556x45_Stanag_Sand_red"; [new - sand]
"30Rnd_556x45_Stanag_red"; [existing class - black]

This system is currently on dev branch. It's not fully functional as yet but you can get an idea of how it works and see the new class names.

**Comment by SamLex** [comment]
Done in FA.3.5.3
