### ISSUE TITLE
[AssignGear] add launcher attachments to f_assignGear_attachments

### ISSUE THREAD

**Issue by NikkoJT** [folkarps/F3#239]
f_assignGear_attachments includes functionality for adding attachments to primary weapons and sidearms. Global Mobilisation adds the possibility of attachments for launchers; assignGear should be modified to handle this, using (presumably) addSecondaryWeaponItem.

**Comment by NikkoJT** [comment]
I see this is assigned to the GM branch, but I don't see why this can't be added to mainline as well. I believe the standard Titan launcher does actually support some rail attachments, and this would improve compatibility with mods for use outside of FA.

**Comment by SamLex** [comment]
Yeah, sorry, I introduced that without really explaining. My idea for the GM branch is that it and the "vanilla" branch will be identical functionality wise. The only different will be the factions in the faction-aware components and template.

For example, the GM branch will probably only have the GM factions and maybe 1 or 2 vanilla factions (3IFB?).

So this change will be going into both the "vanilla" and GM branches.

The idea behind suffixing the release name with '-gm' is to indicate that _most_ of the changes will be on the GM branch; only functional changes on the "vanilla" branch.

**Comment by SamLex** [comment]
Spot tested by setting NATO '_lau_attach1' to "acc_pointer_IR" and added it to '_lau_attachments'. Slotted NATO RAT, MAAWS has IR pointer. Working as intended.
