### ISSUE TITLE
Give full-screen night vision to helipilot classes

### ISSUE THREAD

**Issue by NikkoJT** [folkarps/F3#247]
Per Ciaran, there is a type of magic NVGs (class of which I forget) which have full-screen night vision, without the thermals of the ENVGs. This item could be given to helipilot classes instead of regular NVGs, in order to give them a better night flight experience.

e: per Shado, the class is probably "Integrated_NVG_F"

Requirements:
- define a new gear variable in assignGear for this class
- only add it to heli pilots
- prevent standard NVGs from replacing it when they're added

**Comment by costno** [comment]
No.

**Comment by NikkoJT** [comment]
Solved in #328 by leaving the functionality in place but defaulting to standard NVGs in the definition
