### ISSUE TITLE
Add AI skill handling to Zeus by default

### ISSUE THREAD

**Issue by NikkoJT** [folkarps/F3#249]
Currently, units placed by the F3 template Zeuses are not automatically handled by the AI Skill component.

According to the [AI Skill wiki page](https://github.com/folkarps/F3/wiki/AI-Skill#using-zeus-in-conjunction-with-f3-ai-skill-selector) there is a recommended method for making AI Skill handle Zeus-placed units. I suggest that this be added to F3 Zeus slots by default, so that Zeus units receive AI Skill benefits like increased Courage, and can have their difficulty adjusted as with any mission.

I'm unsure why this hasn't been done in the past - there may be technical issues relating to the event handler, but that would need to be investigated.

**Comment by NikkoJT** [comment]
The wiki is wrong!

**Comment by SamLex** [comment]
Yeah, Zeus units have had AI skill applied since at least 3.4.1. The event handler was potentially bugged, however, but was fixed in 3.5.2. Can you edit the wiki to correct this please?
