### ISSUE TITLE
Change wiki references in comments to refer to the Github wiki

### ISSUE THREAD

**Issue by NikkoJT** [folkarps/F3#251]
Currently, the comments in some locations, such as description.ext, direct users to the original F3 wiki.

However, the original F3 wiki is currently down, and may not return. Also, the original F3 wiki is no longer accurate for this branch of F3 in numerous areas. It would be more useful to the user if these references pointed to the Github wiki for this repository. Although our wiki is not totally complete, it is more up-to-date on many components, and is actually accessible.

**Comment by shadow-fa** [comment]
> // Credits: Please see the F3 online manual (http://www.ferstaberinde.com/f3/en/)

I always thought this was just to credit the people that have worked on a particular component, which are listed on that wiki.

If we remove(/replace) these, we should probably add that credits part to our wiki?

**Comment by NikkoJT** [comment]
We certainly could introduce a credits page, although I'm not sure that's entirely necessary, as being a Github page all contributions are credited to their appropriate users (and the entire thing is credited as a branch of OG F3).

The original F3 wiki is still down, by the way, so linking it doesn't do any good for credits either way.

**Comment by shadow-fa** [comment]
Should we simply remove that credits line or replace it with something?
(That line appears in almost all other sqf files and 24x in init.sqf.)

**Comment by NikkoJT** [comment]
Replace it with a direction to the github wiki. The comment describes itself as a link to the online manual, implying you can read it to find out how to use F3; since the link is both outdated and non-functional, this is misleading and unhelpful. It should direct users to a useful resource (the github wiki).

**Comment by shadow-fa** [comment]
@NikkoJT With what specific text would you replace the old comment (`// Credits: Please see the F3 online manual (http://www.ferstaberinde.com/f3/en/)`) ?

**Comment by NikkoJT** [comment]
`// Credits and documentation: https://github.com/folkarps/F3/wiki`

And add a link to the original fer master on the wiki front page.

**Comment by SamLex** [comment]
For my own peace of mind, I think we should add a credits page to the wiki, either on the landing page or linked from it. Probably based on or linking too the old README's Credits (https://github.com/ferstaberinde/F3/blob/master/README.md). For example, list the "current" contributors and link to that for the full list something like that.

There is also some copyright-y text on there that we should probably have _somewhere_ but idk.
