### ISSUE TITLE
Update briefing ORBAT side annotation

### ISSUE THREAD

**Issue by NikkoJT** [folkarps/F3#265]
Currently, the briefing ORBAT prefixes elements with a letter depending on their side. B for BLUFOR, O for OPFOR, and R for INDFOR. For example, NATO A1 appears in the ORBAT as B NATO A1.

You'll notice the discrepancy; R for INDFOR is actually R for Resistance, another name for the INDFOR side.

I think, and Costno thinks, it would make sense to prefix INDFOR with I instead, if it's practical with how the component is designed.

**Comment by SamLex** [comment]
Is this something we'd want to include in 3.5.4?

**Comment by NikkoJT** [comment]
If Shado can make it happen in 5 minutes, absolutely. I don't think it's worth delaying the release for if it turns out to be more complicated.

**Comment by shadow-fa** [comment]
I believe this is the line that prints these names
https://github.com/folkarps/F3/blob/607be67a1761d17398bcea8a14afe43210371c59/f/briefing/f_orbatNotes.sqf#L60

So the game itself creates that string from the group `_x`.

Do we really need/want to change this?
Do we even want to keep that single letter?
I'd postpone it for the next release unless someone else wants to make it work.

**Comment by shadow-fa** [comment]
Removing that letter is simple. all we need to do is use `groupId _x` instead of just `_x` in that line:
![image](https://user-images.githubusercontent.com/20604336/63792005-f8067f80-c8fc-11e9-8f81-d2cbc45e04cf.png)

**Comment by SamLex** [comment]
I think I'll postpone this to the next release; maybe easy to remove but
unsure if there is a strong opinion around having the side indicating
letter there.
