### ISSUE TITLE
ORBAT notes do not properly handle side marker colors

### ISSUE THREAD

**Issue by darkChozo** [folkarps/F3#267]
The ORBAT notes briefing does not properly handle some vanilla marker colors due to how they're stored in the config. This seems to only affect side colors ("ColorCIV", "ColorWEST", etc) because they define their actual colors relative to profileNamespace and not just as raw values. eg:

    color[] = {"(profilenamespace getvariable ['Map_Unknown_R',0])","(profilenamespace getvariable ['Map_Unknown_G',1])","(profilenamespace getvariable ['Map_Unknown_B',1])","(profilenamespace getvariable ['Map_Unknown_A',0.8])"};

Code that handles this: https://github.com/folkarps/F3/blob/v3.5.3/f/briefing/f_orbatNotes.sqf#L56

**Comment by shadow-fa** [comment]
It looks like they changed something here.
Using this export function, <https://community.bistudio.com/wiki/Arma_3_CfgMarkerColors#Export_Function>
the colors you listed all return [0,0,0] whereas they previously didn't (since the wiki page was generated using that code)
