### ISSUE TITLE
ORBAT notes briefing requires marker colors even for groups without a marker

### ISSUE THREAD

**Issue by darkChozo** [folkarps/F3#279]
If you have an entry in groupData that doesn't specify a marker color, orbatNotes throws an error at line 50, even if a marker is not specified. This is inconsistent with the behavior of the group markers module.

Should be an easy fix; just resolve the marker color config later, and add in a check for whether the marker name is "" before adding the marker image.

repro: something like `["MyGroup","","","","Group - "]` in groupData

**Comment by shadow-fa** [comment]
#268 also seems to have fixed this issue.
