### ISSUE TITLE
Suggestion: add officer class to assignGear_clothes

### ISSUE THREAD

**Issue by darkChozo** [folkarps/F3#285]
A fairly common assignGear thing I've done in my missions is specifying a special officer/boss uniform for leader units. In some cases this is because the CO is meant to be some sort of higher officer or special character, in others it's just to give leader units a beret or something like that. This can also be useful if you're using assignGear_AI and need to distinguish enemy leaders for whatever reason.

Usually, I just use the specOps class for this purpose, but that's a bit of a hack, and obviously a problem if you also want a dedicated spec ops uniform. I feel that this is probably a common enough use case that there should just be a default "officer" class that's automatically handled by assignGear_clothes.

Default officer uniforms could also be specified for some or all factions, though some interpretation might be needed for some factions (spetsnaz: tactical radio plus the future OldMan red beret I guess?).

**Comment by Aqarius90** [comment]
Maybe explicitly call it VIP?
