### ISSUE TITLE
3.5.5 bug tracker

### ISSUE THREAD

**Issue by darkChozo** [folkarps/F3#327]
If 3.5.5 stuff has bugs and you find them, put them here.

3.5.5 changes: https://github.com/folkarps/F3/milestone/9

**Comment by darkChozo** [comment]
Syntax error, missing semi colon here: https://github.com/folkarps/F3/blob/aa815c9388f1320e29327e33c0cac6815d82c536/f/assignGear/f_assignGear_clothes.sqf#L22

**Comment by NikkoJT** [comment]
Created PR #328 for first wave fixes

**Comment by darkChozo** [comment]
Found this by pure chance, but apparently TH4 for LDF and AAF both start with 30% fuel.

https://github.com/folkarps/F3/blob/aa815c9388f1320e29327e33c0cac6815d82c536/mission.sqm#L11726

I searched mission.sqm for "fuel=0." and it only came up with those two.

**Comment by darkChozo** [comment]
#265 - letter prefix was not removed from vehicle cargo groups

![20210311224928_1](https://user-images.githubusercontent.com/11525430/110889415-16a05180-82bc-11eb-9b8b-56dc949ecd90.jpg)

**Comment by darkChozo** [comment]
NPR technicals have different slotting screen orders.

Also some of these obviously aren't 3.5.5-related issues, so if we don't want to tackle them now we could probably just spin them off into their own issues.

<details>
<summary>Picture</summary>

![20210311231034_1](https://user-images.githubusercontent.com/11525430/110890997-0c338700-82bf-11eb-9834-192ca5a14737.jpg)

</details>

**Comment by shadow-fa** [comment]
> 
> 
> #265 - letter prefix was not removed from vehicle cargo groups
> Picture

https://github.com/folkarps/F3/blob/master/f/briefing/f_orbatNotes.sqf#L146
I suspect that this line needs to change like that (untested):
```diff
-_orbatText =_orbatText + format["%1%2 %3", _icon_arrow, _icon, _x] + " [CARGO] <br />";
+_orbatText =_orbatText + format["%1%2 %3", _icon_arrow, _icon, groupId _x] + " [CARGO] <br />";
```

**Comment by darkChozo** [comment]
Turns out the assignGear stuff in createGarrison is bugged. This throws errors:

https://github.com/folkarps/F3/blob/aa815c9388f1320e29327e33c0cac6815d82c536/ws_fnc/AI/fn_createGarrison.sqf#L234

I think it should be this, but it should be tested:

	{
		[_x,_assignGearFaction] remoteExec ["f_fnc_setVirtualFaction",2];
	} forEach units _grp;
	[units _grp,"f\assignGear\f_assignGear_AI.sqf"] remoteExec ["execVM",2];

**Comment by darkChozo** [comment]
Also Spetsnaz don't get weapons when assignGear_AI'd through createGarrison. Though that's probably just because assignGear_AI doesn't support them though.

**Comment by NikkoJT** [comment]
assignGear AI does support all classnames used by the default Spetsnaz classes in createGarrison. If it didn't, they would just have their default BI loadouts. There must be another problem.

Can you confirm whether Spetsnaz work properly when done with player assignGear?

**Comment by darkChozo** [comment]
Tried it, didn't work. Think I see a bit of an issue:

https://github.com/folkarps/F3/blob/aa815c9388f1320e29327e33c0cac6815d82c536/f/assignGear/f_assignGear_spetsnaz.sqf#L383

**Comment by NikkoJT** [comment]
Yes, just found and fixed that. That would be the problem - that's the part with all the guns, while assignGear_clothes is run separately.

**Comment by darkChozo** [comment]
#279 - when side color is blank, you still get an error. It's the kind that appears at the bottom of the screen in a black bar, but it's still an error.

**Comment by shadow-fa** [comment]
> #279 - when side color is blank, you still get an error. It's the kind that appears at the bottom of the screen in a black bar, but it's still an error.

I'm not sure this is a bug we should fix since the other group marker behaviour (with the empty string) relies on undefined /undocumented behaviour of `setMarkerColorLocal`

**Comment by darkChozo** [comment]
The main issue IIRC is that you shouldn't have to specify a marker color if you're not giving a group a marker. Currently you do have to put in a dummy color or else it errors.

Further discussion should probably be in that issue btw, not here.

**Comment by darkChozo** [comment]
Realized another createGarrison issue. addCuratorEditableObjects is server-only so it needs to be remoteExeced too.

https://github.com/folkarps/F3/blob/aa815c9388f1320e29327e33c0cac6815d82c536/ws_fnc/AI/fn_createGarrison.sqf#L248

**Comment by darkChozo** [comment]
Found another thing, apparently the Gendarmerie assignGear file doesn't define the clothing variables (_jet, _crew, etc), which causes a script error in assignGear_clothes. I'm pretty sure this is just an existing issue that no one noticed because we never use the gendarme file.

**Comment by NikkoJT** [comment]
Not a 3.5.5 issue. Raised as #337

**Comment by darkChozo** [comment]
Missing semicolon in cascap:

https://github.com/folkarps/F3/blob/9c848d2978a2bc4b8f9a833b03652ab740a5c551/f/casualtiesCap/f_CasualtiesCapCheck.sqf#L130

**Comment by NikkoJT** [comment]
#338 in progress for second pass fixes
