### ISSUE TITLE
__has_include to fix #include crashing

### ISSUE THREAD

**Issue by darkChozo** [folkarps/F3#331]
Apparently BI added in a [__has_include preprocessor command](https://community.bistudio.com/wiki/PreProcessor_Commands#has_include) in 2.01, that should let us check if a file exists before we try to #include it. This probably fixes the #include crashing issue, which means that you can delete unnecessary files without having to modify fn_assignGear or fn_createBriefing.

Usage would probably be something like this:

    #if __has_include("f_assignGear_3IFB.sqf")
        #include "f_assignGear_3IFB.sqf"
    #endif

**Comment by darkChozo** [comment]
PR'd the basic changes, but I think there's probably other areas where this can be applied. Ex. in assignGear files themselves, so they error if you delete a _standard or _v file instead of crashing. Though there might be a complexity issue there since that's code that's likely to be touched by newbies.

**Comment by NikkoJT** [comment]
I think it's okay to leave a crash in that case since a missing loadouts file is something that _must not_ be overlooked.
