### ISSUE TITLE
Change AAF and FIA AR to LIM-85

### ISSUE THREAD

**Issue by costno** [folkarps/F3#346]
AAF still uses the standard AAF autorifleman weapon (MK200 6.5mm) several years after the addition of a 5.56 belt fed that is more appropriate (logistics considerations with rifle ammo). 

They should use the LIM-85 instead.

Same goes for FIA who would likely use the available AR captured from AAF.

**Comment by darkChozo** [comment]
Might want to do an explicit host discussion on this. I kinda like it though.

**Comment by flyinghat** [comment]
Vote aye. The LIM is fun and would change things up in sessions.

**Comment by NikkoJT** [comment]
All respondents in a host poll voted for this change.

**Comment by NikkoJT** [comment]
Fixed in 3.5.6
