### ISSUE TITLE
[assignGear] change vehicle cargo weapons to addWeaponWithAttachmentsCargoGlobal

### ISSUE THREAD

**Issue by NikkoJT** [folkarps/F3#361]
An upcoming change (https://feedback.bistudio.com/T63451) is expected to remove the behaviour where grabbing a weapon out of a container auto-loads it with an appropriate magazine if one is in the container.

To preserve this behaviour in F3 (simulating weapons being already loaded in vehicle cargo, esp. launchers), where weapons are added to cargo in F3, the command should be changed to `addWeaponWithAttachmentsCargoGlobal`. This will ensure players continue to see the behaviour they're used to, and as a bonus adds better compatibility with CDLC disposable launchers.

**Comment by SamLex** [comment]
My reading of the linked change is that this only changes picking up an empty weapon auto-loading from magazines in the _player's inventory_. The comments seem to explicitly say this won't impact taking weapons from containers using mags from the container itself

> Technically it is possible to extend it for the containers but this is quite a game changer and I need to consult on this, but my gut feeling tells me it is unlikely to happen

**Comment by NikkoJT** [comment]
Well, the comment on the FT that says that was written after I wrote this change :U

I don't trust that that will remain true forever, and this is still better for disposable launchers, as well as helping to ensure that a stowed weapon has at least 1 magazine that hasn't been stolen to be used by someone else.
