### ISSUE TITLE
Expand disableThermals components to player unit thermals

### ISSUE THREAD

**Issue by SamLex** [folkarps/F3#375]
Currently, the `disableThermals` components only disable thermal imaging on vehicles and UAVs. This could be expanded to player unit thermals, such as headsets, thermal scopes, launchers with thermal scopes, etc.

If we want to do this, need to confirm that `disableTIEquipment` actually works on a player unit.

**Comment by NikkoJT** [comment]
`disableTIEquipment` does not work on infantry units.

**Comment by SamLex** [comment]
There goes that idea then, probably why it wasn't done originally
