### ISSUE TITLE
Some medic(al) ideas

### ISSUE THREAD

**Issue by SamLex** [folkarps/F3#71]
- Some form of UI feedback when people are being healed (e.g. fade in text at center-bottom of screen along the lines of "You are being healed by X")
- Some form of UI feedback to show level of wounds (this is difficult and perhaps 'gamey ' but vanilla makes it really difficult to tell, leading to people asking for medic when they don't need it or not asking when they do need it)
- ~~If possible: turning around and moving slightly doesn't disturb healing process~~ 
Edit Shado': This has been adressed with the Tank? update.

**Comment by shadow-fa** [comment]
* Some form of UI feedback when doing the action, because it fades away during the revive. (Due to server difficulty settings?)

**Comment by SamLex** [comment]
> because it fades away during the revive. 
I think this only happens when you scroll wheel to see the action (vs just 'hovering over' the player to be revived). Could be a server difficulty setting, not sure, seems more like a BI bug as it happens at the same time the action menu fades out

**Comment by NikkoJT** [comment]
Closing this because everything here is addressed by FA Medical #385
