### ISSUE TITLE
The String(table) Refactor

### ISSUE THREAD

**Issue by SamLex** [folkarps/F3#83]
I propose moving all strings that are currently defined in SQF code into stringtable.xml, where they can be referenced from within code using `localize`. This has several advantages:

- Central location to update and change strings; don't need to go find where a string is being used to change it
- SQF code gets slimed down a bit, and can be focused on function
- External editors, such as StringForge, can be used to edit stringtable.xml, making changes even easier
- Much easier internationalization (not a huge advantage for FA usage I'll admit)
- Briefing component can be reduced to a single SQF file! With all briefing content being defined in stringtable.xml

**On Briefing**
The briefing component currently has one file per-faction where each section of the briefing is defined. Moving these definitions to stringtable.xml would mean the briefing code could be greatly generalised, making it cleaner and easier to maintain. A missionmaker would also not need to edit SQF code to add their briefing, instead having to edit the stringtable.xml which could be done through an external tool such as StringForge.

To give an example of how this might work, the "Administration" section of the AAF briefing could be put in the stringtable.xml under the key 'f_briefing_aaf_administration'. The briefing code could then fetch this by getting the faction of the player it is generating the briefing for (in this example, AAF) and generate the key above as 'f_briefing_<faction of player>_administration'. This concept would then be applied for each section of the briefing.

"What of conditional briefings?" you may ask. The briefing code could look for two functions per section that a missionmaker could define (for example, in init.sqf) before the briefing generation is run. These would be a 'chooser' function (named, for example, 'f_briefing_<faction>_<section>_chooser') and a 'formatter' function (named, for example, 'f_briefing_<faction>_<section>_formatter').

The 'chooser' function would not be passed in arguments and would, based on whatever condition the missionmaker wished, return a stringtable key for that section of the briefing. For example, based on the value of a mission parameter it could return 'my_cool_briefing_section' or 'my_awesome_briefing_section'.

The 'formatter' function would take the key of the briefing section being generated and the dereferenced text itself, and return the formatted code. This would allow `format` wildcards to replaced by whatever values the missionmaker desired.

These functions would be entirely optional, only needed if the briefing required dynamic data, and the briefing code would only attempt to use them if they were defined.

**Comment by shadow-fa** [comment]
It should be noted that the stringtable also works for in-editor fields (in `mission.sqm`). 
Strings for the fields `Author`, `Title`, `Loading Screen Text`, and `Lobby Summary` could be defined in the stringtable and also be used for the `onLoadName` in `description.ext` as well as the briefing (e.g. Credits #145). This has the advantage of having only a single file where the missionmaker has to enter strings.

**Comment by CSDGC** [comment]
With current streamlining proposals, this no longer seems relevant as stringtable.xml is likely to be scrapped.
